### PR TITLE
Minor fixes.

### PR DESCRIPTION
**Pull request by bhw-foss**
Howdy. Hope the weather in Germany is treating you nice. I'm eager to try out
your library, but after getting it to load, I'm running into a bunch of error
conditions. I reproduced the steps below,

``` common-lisp
CL-USER> (asdf:load-system :cl-tbnl-gserver-tmgr)
WARNING: System definition file #P"/home/ben/quicklisp/dists/quicklisp/software/hunchentoot-v1.3.0/hunchentoot.asd" contains definition for system "hunchentoot-test". Please only define "hunchentoot" and secondary systems with a name starting with "hunchentoot/" (e.g. "hunchentoot/test") in that file.
WARNING: System definition file #P"/home/ben/quicklisp/dists/quicklisp/software/hunchentoot-v1.3.0/hunchentoot.asd" contains definition for system "hunchentoot-dev". Please only define "hunchentoot" and secondary systems with a name starting with "hunchentoot/" (e.g. "hunchentoot/test") in that file.
;;; Computing Hangul syllable names
WARNING: redefining LOG4CL-IMPL:APPENDER-ADDED in DEFGENERIC
WARNING: redefining LOG4CL-IMPL:APPENDER-REMOVED in DEFGENERIC
WARNING: redefining LOG4CL-IMPL::PROPERTY-ALIST in DEFGENERIC
T
CL-USER>
TMGR> (let ((acceptor (make-instance 'tbnl:easy-acceptor
                                 :port 4242
                                 :taskmaster (make-instance 'gserver-tmgr
                                                            :max-thread-count 8))))
  (tbnl:start acceptor))
 <INFO> [12:55:17] cl-tbnl-gserver-tmgr.tmgr tmgr.lisp () - Spawning 8 routees.
execute acceptor...
#<EASY-ACCEPTOR (host *, port 4242)>
<ERROR> [> [COMMON-LISP-USER] ] actor-40a: error8: erior conditioiseas raised:
invalid number of a:guments: 3


<ERROR> [COMMON-LISP-USER] actor-404: error condition was raised:
invalid number of arguments: 3


<ERROR> [COMMON-LISP-USER] actor-404: error condition was raised:
invalid number of arguments: 3
:guments: 3

<ERROR> [COMMON-LISP-USER] actor-408: error condition was raised:
invalid number of arguments: 3

<ERROR> [COMMON-LISP-USER] actor-406: error condition was raised:
invalid number of arguments: 3

<ERROR> [COMMON-LISP-USER] actor-402: error condition was raised:
invalid number of arguments: 3

<ERROR> [COMMON-LISP-USER] actor-396: error condition was raised:
invalid number of arguments: 3


<ERROR> [COMMON-LISP-USER] actor-402: error condition was raised:
invalid number of arguments: 3

<ERROR> [COMMON-LISP-USER] actor-396: error condition was raised:
invalid number of arguments: 3

<ERROR> [COMMON-LISP-USER] actor-400: error condition was raised:
invalid number of arguments: 3
```

I fixed some minor issues but I have a feeling I'm missing something. Any
pointers? Thanks for your time,

### CODE REVIEW

**Comment by mdbergmann** [comment]
Yeah, I think this wasn't updated in a while.
cl-gserver API has changed a bit.
I'll check.

**Comment by mdbergmann** [comment]
So, I have updated the code. All tests pass.
Unfortunately your PR is now obsolete. But thanks for giving it a try.

**Comment by mdbergmann** [comment]
Though I would take the README update if you don't mind.

**Comment by bhw-foss** [comment]
No problem. Thank you, and Godspeed.

**Review by mdbergmann — APPROVED** [review]

**Comment by bhw-foss** [comment]
Awesome, thanks again Manfred! My personal website is now almost twice
as fast!

Intel i5-6300U, 8GB RAM

1. Default out of the box hunchentoot server.

***@***.***:~/Dropbox/project-maria/blog$ wrk -t4 -c100 -d10 "http://localhost:4242/yo"
Running 10s test @ http://localhost:4242/yo
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    59.75ms  192.66ms   1.67s    94.85%
    Req/Sec     1.64k     0.87k    5.81k    70.40%
  48584 requests in 10.10s, 20.76MB read
  Socket errors: connect 0, read 0, write 0, timeout 53
  Non-2xx or 3xx responses: 48584
Requests/sec:   4810.99
Transfer/sec:      2.06MB

With cl-gserver,

***@***.***:~/Dropbox/project-maria/blog$ wrk -t4 -c100 -d10 "http://localhost:4242/yo"
Running 10s test @ http://localhost:4242/yo
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.67ms   17.11ms 496.46ms   99.61%
    Req/Sec     5.02k     3.78k   10.94k    61.46%
  96259 requests in 10.07s, 41.13MB read
  Non-2xx or 3xx responses: 96259
Requests/sec:   9555.08
Transfer/sec:      4.08MB

2. Incorporating into my application (generates some HTML with spinneret)

***@***.***:~/Dropbox/project-maria/blog$ wrk -t4 -c100 -d10 "http://localhost:8080/about"
Running 10s test @ http://localhost:8080/about
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   152.84ms  212.42ms   1.91s    89.16%
    Req/Sec   263.41    197.28     0.87k    67.26%
  8097 requests in 10.06s, 15.07MB read
  Socket errors: connect 0, read 0, write 0, timeout 36
Requests/sec:    804.71
Transfer/sec:      1.50MB

With cl-gserver,

***@***.***:~/Dropbox/project-maria/blog$ wrk -t4 -c100 -d10 "http://localhost:8080/about"
Running 10s test @ http://localhost:8080/about
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     9.51ms   57.93ms   1.19s    98.96%
    Req/Sec     1.61k   424.05     2.12k    83.52%
  14605 requests in 10.03s, 27.17MB read
Requests/sec:   1456.28
Transfer/sec:      2.71MB

**Comment by mdbergmann** [comment]
Cool. I should use it also for my web page. :)

**Pull request merged**
